version: '3.9'

services:
  web:
    build: .
    command: flask db upgrade && gunicorn -b 0.0.0.0:5000 src:app
    ports:
      - "5000:5000"
    environment:
      - FLASK_CONFIG=${FLASK_CONFIG}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: soto2571
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: soto2571
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: