"""Initial migration

Revision ID: e55c4141791f
Revises: 7a4581e747fd
Create Date: 2024-06-25 16:11:54.066772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55c4141791f'
down_revision = '7a4581e747fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'password_hash',
                sa.String(
                    length=128),
                nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'password',
                sa.VARCHAR(
                    length=128),
                nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
